### ISSUE TITLE
Can't get current selected date

### ISSUE THREAD

**Issue by ghost** [RafalManka/ScrollCalendar#4]
Hi,

Is possible get current selected date, without using the setOnDateClickListener?

**Comment by RafalManka** [comment]
By design, the widget is not aware of any state. The purpose of that was that is that you are going to store the selected date probably somewhere in the presenter or in activity/fragment in order to have better control.

Take a look at the included examples project. You have selected date stored as a Date object in this case. 

The widget only cares about what DateWatcher#getStateForDate returns. You don't even have to implement OnDateClickListener#setOnDateClickListener to display selected date (or even multiple dates?) on a calendar. I was going for maximum flexibility and control.

@VictorFernandes would that answer your question or maybe I should include another example to better explain how it works?

**Comment by ghost** [comment]
@RafalManka your answer clarified for my development but you should keep in mind that you are developing a custom view and as a custom view you need provide access to information other way than only listeners maybe someone somewhere would need this kind of feature.
